<?php

namespace CoreBundle\Repository\Information;

/**
 * RatingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingsRepository extends \Doctrine\ORM\EntityRepository
{
}
