<?php

namespace CoreBundle\Repository\Music;

/**
 * ArtworkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtworkRepository extends \Doctrine\ORM\EntityRepository
{
}
